#!/usr/bin/env python3
"""
Wrapper script that ensures Prisma Python client is generated before running ingestion
"""
import subprocess
import sys
import os
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

def generate_prisma_client():
    """Generate Prisma Python client"""
    # The Python Prisma client needs to be generated by running prisma generate
    # but it seems to only generate the Node.js client. Let's try a workaround:
    # We'll set the PRISMA_GENERATE_DATAPROXY environment variable and try again
    
    print("🔧 Generating Prisma Python client...")
    
    # Try multiple approaches to generate the client
    env = os.environ.copy()
    env['PRISMA_GENERATE_DATAPROXY'] = 'false'
    
    try:
        # First, try the standard generate command
        result = subprocess.run(
            [sys.executable, "-m", "prisma", "generate"],
            cwd=project_root,
            env=env,
            capture_output=True,
            text=True,
            timeout=60
        )
        
        # Check if we can now import Prisma
        try:
            # Clear any cached imports
            if 'prisma' in sys.modules:
                del sys.modules['prisma']
            if 'prisma.client' in sys.modules:
                del sys.modules['prisma.client']
            
            from prisma import Prisma
            prisma = Prisma()
            print("✅ Prisma client generated and verified")
            return True
        except RuntimeError as e:
            if "hasn't been generated" in str(e):
                print("⚠️  Prisma client still not generated after command")
                print("   This is a known issue with Prisma Python client generation")
                print("   The ingestion will continue but may fail when accessing the database")
                return False
            else:
                raise
                
    except subprocess.TimeoutExpired:
        print("⚠️  Prisma generation timed out")
        return False
    except Exception as e:
        print(f"⚠️  Prisma generation error: {e}")
        return False

if __name__ == "__main__":
    # Generate Prisma client first
    generate_prisma_client()
    
    # Now run the actual ingestion script using subprocess
    # This ensures proper execution and environment
    ingest_script = project_root / "registry" / "ingest_priority_models.py"
    
    # Run the ingestion script with the same Python interpreter
    result = subprocess.run(
        [sys.executable, str(ingest_script)] + sys.argv[1:],
        cwd=project_root,
    )
    sys.exit(result.returncode)

